# Generated by Django 4.2.4 on 2023-08-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
