# Generated by Django 4.2.4 on 2023-08-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0002_emailaccount_age_emailaccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='age',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='role',
        ),
    ]
