# Generated by Django 4.2.4 on 2023-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0003_remove_emailaccount_age_remove_emailaccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
