# Generated by Django 4.2.4 on 2023-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0004_emailaccount_age_emailaccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='age',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='role',
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
