# Generated by Django 4.2.4 on 2023-08-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0006_emailaccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
