# Generated by Django 4.2.4 on 2023-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhis', '0002_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(null=True, upload_to='patient_images'),
        ),
    ]
